# Generated by Django 3.0.5 on 2021-02-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newops', '0004_auto_20210223_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='CAtype',
            field=models.CharField(choices=[('Self', 'Self'), ('CA', 'CA')], default=None, max_length=100),
        ),
    ]
